//
//  ThemeManager.swift
//  PowderMeet
//
//  A Theme bundles three things into a single named pick:
//
//    • icon  — the home-screen AppIcon variant
//      (`UIApplication.setAlternateIconName(_:)`)
//    • text  — the HUD accent color used for labels, chrome, selected
//      states (`HUDTheme.accent` reads this through Swift Observation
//      tracking, so changes ripple process-wide without manual
//      invalidation)
//    • bg    — the app's root background tint, near-black with a
//      whisper of hue so the theme's identity reads on every sheet
//      and root surface (`HUDTheme.mapBackground`)
//
//  The launch ORIGINAL theme keeps the legacy black background; every
//  other theme tints the bg toward its accent (~5–10% luminance) so
//  the chrome reads as belonging to that theme without ever stealing
//  contrast from the content on top.
//
//  Source of truth for the metadata below lives in
//  `tools/generate_theme_icons.py`. That script also generates the
//  icon PNGs and emits the Info.plist `CFBundleAlternateIcons` block.
//  Edit the script first, paste its output into this file second.
//

import SwiftUI
import UIKit

@MainActor
@Observable
final class ThemeManager {
    static let shared = ThemeManager()

    // MARK: - Theme

    enum Theme: String, CaseIterable, Identifiable {

        // ── Normal — the launch eight ──
        case original
        case glacier
        case sunset
        case carbon

        // ── Unique — generated by tools/generate_theme_icons.py ──
        case bluebird
        case emerald
        case lagoon
        case rose
        case solar
        case pine
        case sapphire
        case lavender
        case violet
        case cherry
        case magenta
        case mintFrost
        case ember
        case powder
        case whiteout
        case aurora
        case fireside
        case timber
        case evergreen
        case moonlit
        case nebula
        case infrared
        case retro
        case stardust
        case crevasse

        // ── Round 2: round PURE COLORS to 25 (5 new) and COMBOS to
        // 30 (5 new). Total catalog: 60 themes = 5 + 25 + 30.
        case olive
        case tidepool

        // ── Bespoke variants (tools/generate_core_icons.py) ──
        // A 2nd Retro colorway + four recolored Aurora gradients.
        case retroIce
        case auroraDawn
        case auroraEmber
        case auroraIce
        case auroraRose

        var id: String { rawValue }

        /// The picker section a theme belongs to. This is the single
        /// source of truth for both the grouped picker layout AND the
        /// per-section typeface (see `fontDesign`). CORE is just the
        /// brand mark; SPECTRUM is every pure single-tone hue; TECH is
        /// the fixed neon/HUD five; NATURE is everything scenic
        /// (Aurora + its recolors lead it).
        // Declaration order = picker section order: CORE, TECH,
        // NATURE, SPECTRUM (`Section.allCases` drives the layout).
        enum Section: String, CaseIterable {
            case core, tech, nature, spectrum
        }

        var section: Section {
            switch self {
            case .original:
                return .core
            case .retro, .retroIce, .infrared, .whiteout, .carbon:
                return .tech
            case .bluebird, .cherry, .ember, .emerald, .glacier,
                 .lagoon, .lavender, .magenta, .mintFrost, .olive,
                 .pine, .rose, .sapphire, .solar, .violet:
                return .spectrum
            // NATURE — Aurora + its four recolors, then the curated
            // scenic combos. Default so a new scenic theme lands here
            // rather than vanishing from the picker.
            default:
                return .nature
            }
        }

        var label: String {
            switch self {
            case .original: return "ORIGINAL"
            case .glacier: return "GLACIER"
            case .sunset: return "SUNSET"
            case .carbon: return "CARBON"
            case .bluebird: return "BLUEBIRD"
            case .emerald: return "EMERALD"
            case .lagoon: return "LAGOON"
            case .rose: return "ROSE"
            case .solar: return "SOLAR"
            case .pine: return "PINE"
            case .sapphire: return "SAPPHIRE"
            case .lavender: return "LAVENDER"
            case .cherry: return "CHERRY"
            case .magenta: return "MAGENTA"
            case .mintFrost: return "MINT FROST"
            case .ember: return "EMBER"
            case .powder: return "POWDER"
            case .whiteout: return "WHITEOUT"
            case .aurora: return "AURORA"
            case .fireside: return "FIRESIDE"
            case .timber: return "TIMBER"
            case .evergreen: return "EVERGREEN"
            case .moonlit: return "MOONLIT"
            case .nebula: return "NEBULA"
            case .infrared: return "INFRARED"
            case .retro: return "RETRO"
            case .stardust: return "STARDUST"
            case .crevasse: return "CREVASSE"
            case .olive: return "OLIVE"
            case .tidepool: return "TIDEPOOL"
            case .violet: return "VIOLET"
            case .retroIce: return "RETRO ICE"
            case .auroraDawn: return "AURORA DAWN"
            case .auroraEmber: return "AURORA EMBER"
            case .auroraIce: return "AURORA ICE"
            case .auroraRose: return "AURORA ROSE"
            }
        }

        var subtitle: String {
            switch self {
            case .original: return "RED + BLACK PEAKS"
            case .glacier: return "COOL CYAN"
            case .sunset: return "PINK + ORANGE PEAKS"
            case .carbon: return "GRAPHITE + GUNMETAL"
            case .bluebird: return "PURE SKY BLUE"
            case .emerald: return "DEEP EMERALD"
            case .lagoon: return "TURQUOISE LAGOON"
            case .rose: return "DUSTY ROSE"
            case .solar: return "GOLDEN YELLOW"
            case .pine: return "DEEP PINE"
            case .sapphire: return "DEEP SAPPHIRE"
            case .lavender: return "SOFT LAVENDER"
            case .cherry: return "CHERRY RED"
            case .magenta: return "VIVID MAGENTA"
            case .mintFrost: return "ICY MINT"
            case .ember: return "GLOWING EMBER"
            case .powder: return "ICE BLUE + FROST"
            case .whiteout: return "FOG + LIGHT GRAY"
            case .aurora: return "TEAL + VIOLET"
            case .fireside: return "EMBER + CHARCOAL"
            case .timber: return "PINE + WALNUT"
            case .evergreen: return "FOREST + SAGE"
            case .moonlit: return "SILVER + DEEP BLUE"
            case .nebula: return "PURPLE + MAGENTA"
            case .infrared: return "MAGENTA + DEEP RED"
            case .retro: return "MAGENTA + GOLD"
            case .stardust: return "VIOLET + LAVENDER"
            case .crevasse: return "ICE + DEEP NAVY"
            case .olive: return "OLIVE GREEN"
            case .tidepool: return "TURQUOISE + SAND"
            case .violet: return "PURE VIOLET"
            case .retroIce: return "CYAN + VIOLET"
            case .auroraDawn: return "MAGENTA + GOLD"
            case .auroraEmber: return "CRIMSON + AMBER"
            case .auroraIce: return "CYAN + MINT"
            case .auroraRose: return "MAGENTA + ROSE"
            }
        }

        /// Typeface is now driven by the theme's SECTION, not the
        /// individual theme — every theme in a section shares one of
        /// SwiftUI's four system designs so the section reads as a
        /// coherent family:
        ///   • CORE / TECH → monospaced — instrument-panel / HUD
        ///   • SPECTRUM    → default    — clean face lets the pure hue
        ///                                carry the identity
        ///   • NATURE      → rounded    — soft / organic / scenic
        var fontDesign: Font.Design {
            switch section {
            case .core, .tech: return .monospaced
            case .spectrum:    return .default
            case .nature:      return .rounded
            }
        }

        /// (peak, base) hex pair used to recolor the alternate icon
        /// AND to render the two color swatches under the picker grid
        /// cell. Single-tone themes set peak == base. Source of truth
        /// lives in `tools/generate_theme_icons.py`; this switch is
        /// emitted by that script for paste-back here.
        private var swatchHexes: (peak: String, base: String) {
            switch self {
            case .original: return ("E63333", "0F0F0F")
            case .glacier: return ("73D6FF", "73D6FF")
            case .sunset: return ("FF4D6D", "FF8A3D")
            case .carbon: return ("6B7280", "1F2937")
            case .bluebird: return ("4DA6FF", "4DA6FF")
            case .emerald: return ("10B981", "10B981")
            case .lagoon: return ("06B6D4", "06B6D4")
            case .rose: return ("F472B6", "F472B6")
            case .solar: return ("F59E0B", "F59E0B")
            case .pine: return ("166534", "166534")
            case .sapphire: return ("2563EB", "2563EB")
            case .lavender: return ("A78BFA", "A78BFA")
            case .cherry: return ("DC2626", "DC2626")
            case .magenta: return ("D946EF", "D946EF")
            case .mintFrost: return ("A7F3D0", "A7F3D0")
            case .ember: return ("EA580C", "EA580C")
            case .powder: return ("7DD3FC", "E0F2FE")
            case .whiteout: return ("9CA3AF", "D1D5DB")
            case .aurora: return ("22D3EE", "A855F7")
            case .fireside: return ("F97316", "374151")
            case .timber: return ("92400E", "365314")
            case .evergreen: return ("A3E635", "14532D")
            case .moonlit: return ("CBD5E1", "1E3A8A")
            case .nebula: return ("7C3AED", "EC4899")
            case .infrared: return ("E11D48", "9F1239")
            case .retro: return ("FF3D81", "FFC24B")
            case .stardust: return ("7C3AED", "C4B5FD")
            case .crevasse: return ("38BDF8", "1E3A8A")
            case .olive: return ("84CC16", "84CC16")
            case .tidepool: return ("06B6D4", "FED7AA")
            case .violet: return ("7C3AED", "7C3AED")
            case .retroIce: return ("22D3EE", "A855F7")
            case .auroraDawn: return ("FBBF24", "D9468C")
            case .auroraEmber: return ("F59E0B", "9F1239")
            case .auroraIce: return ("22D3EE", "5EEAD4")
            case .auroraRose: return ("F472B6", "7C3AED")
            }
        }

        /// Color above the snow line on the icon's mountains. Picker
        /// renders this as the first swatch under each cell.
        var peakColor: Color { Color(hex: swatchHexes.peak) }

        /// Color below the snow line on the icon's mountains. Picker
        /// renders this as the second swatch under each cell. For
        /// single-tone themes equals `peakColor`.
        var baseColor: Color { Color(hex: swatchHexes.base) }

        /// True when peak + base disagree — picker draws two distinct
        /// swatches; otherwise one wider swatch reads cleaner.
        var isTwoTone: Bool { swatchHexes.peak != swatchHexes.base }

        /// Process-wide TEXT accent — labels, chrome, selected states.
        /// `HUDTheme.accent` proxies through `ThemeManager.shared.activeTheme.accentColor`.
        var accentColor: Color {
            switch self {
            case .original: return Color(red: 0.922, green: 0.200, blue: 0.200)
            case .glacier: return Color(red: 0.451, green: 0.839, blue: 1.000)
            case .sunset: return Color(red: 1.000, green: 0.361, blue: 0.498)
            case .carbon: return Color(red: 0.420, green: 0.447, blue: 0.502)
            case .bluebird: return Color(red: 0.302, green: 0.651, blue: 1.000)
            case .emerald: return Color(red: 0.063, green: 0.725, blue: 0.506)
            case .lagoon: return Color(red: 0.024, green: 0.714, blue: 0.831)
            case .rose: return Color(red: 0.957, green: 0.447, blue: 0.714)
            case .solar: return Color(red: 0.961, green: 0.620, blue: 0.043)
            case .pine: return Color(red: 0.133, green: 0.651, blue: 0.345)
            case .sapphire: return Color(red: 0.231, green: 0.510, blue: 0.965)
            case .lavender: return Color(red: 0.655, green: 0.545, blue: 0.980)
            case .cherry: return Color(red: 0.937, green: 0.267, blue: 0.267)
            case .magenta: return Color(red: 0.851, green: 0.275, blue: 0.937)
            case .mintFrost: return Color(red: 0.369, green: 0.918, blue: 0.831)
            case .ember: return Color(red: 0.976, green: 0.451, blue: 0.086)
            case .powder: return Color(red: 0.490, green: 0.827, blue: 0.988)
            case .whiteout: return Color(red: 0.612, green: 0.639, blue: 0.686)
            case .aurora: return Color(red: 0.133, green: 0.827, blue: 0.933)
            case .fireside: return Color(red: 0.976, green: 0.451, blue: 0.086)
            case .timber: return Color(red: 0.518, green: 0.800, blue: 0.086)
            case .evergreen: return Color(red: 0.396, green: 0.639, blue: 0.051)
            case .moonlit: return Color(red: 0.796, green: 0.835, blue: 0.882)
            case .nebula: return Color(red: 0.659, green: 0.333, blue: 0.969)
            case .infrared: return Color(red: 0.882, green: 0.114, blue: 0.282)
            case .retro: return Color(red: 1.000, green: 0.239, blue: 0.506)
            case .stardust: return Color(red: 0.769, green: 0.710, blue: 0.992)
            case .crevasse: return Color(red: 0.220, green: 0.741, blue: 0.973)
            case .olive: return Color(red: 0.518, green: 0.800, blue: 0.086)
            case .tidepool: return Color(red: 0.024, green: 0.714, blue: 0.831)
            case .violet: return Color(red: 0.486, green: 0.227, blue: 0.929)
            case .retroIce: return Color(red: 0.133, green: 0.827, blue: 0.933)
            case .auroraDawn: return Color(red: 0.984, green: 0.749, blue: 0.141)
            case .auroraEmber: return Color(red: 0.961, green: 0.620, blue: 0.043)
            case .auroraIce: return Color(red: 0.133, green: 0.827, blue: 0.933)
            case .auroraRose: return Color(red: 0.957, green: 0.447, blue: 0.714)
            }
        }

        /// RGB components of the theme's root background tint. Used
        /// to derive every other surface tier (card, input, header,
        /// border) at compile time so the whole tonal stack inherits
        /// the theme's hue while preserving the bg < header < input <
        /// card < border luminance ladder.
        private var bgRGB: (r: Double, g: Double, b: Double) {
            switch self {
            case .original: return (0.059, 0.059, 0.071)
            case .glacier: return (0.031, 0.071, 0.102)
            case .sunset: return (0.098, 0.039, 0.063)
            case .carbon: return (0.055, 0.063, 0.078)
            case .bluebird: return (0.027, 0.059, 0.102)
            case .emerald: return (0.024, 0.078, 0.059)
            case .lagoon: return (0.024, 0.078, 0.102)
            case .rose: return (0.090, 0.043, 0.071)
            case .solar: return (0.086, 0.059, 0.024)
            case .pine: return (0.024, 0.071, 0.039)
            case .sapphire: return (0.027, 0.043, 0.110)
            case .lavender: return (0.063, 0.035, 0.102)
            case .cherry: return (0.090, 0.027, 0.027)
            case .magenta: return (0.082, 0.031, 0.094)
            case .mintFrost: return (0.031, 0.078, 0.102)
            case .ember: return (0.086, 0.039, 0.016)
            case .powder: return (0.031, 0.071, 0.102)
            case .whiteout: return (0.063, 0.071, 0.086)
            case .aurora: return (0.031, 0.071, 0.102)
            case .fireside: return (0.078, 0.039, 0.024)
            case .timber: return (0.039, 0.059, 0.024)
            case .evergreen: return (0.031, 0.071, 0.039)
            case .moonlit: return (0.027, 0.035, 0.102)
            case .nebula: return (0.063, 0.024, 0.094)
            case .infrared: return (0.082, 0.024, 0.043)
            case .retro: return (0.067, 0.031, 0.090)
            case .stardust: return (0.063, 0.031, 0.094)
            case .crevasse: return (0.027, 0.039, 0.102)
            case .olive: return (0.055, 0.071, 0.024)
            case .tidepool: return (0.039, 0.063, 0.078)
            case .violet: return (0.047, 0.031, 0.094)
            case .retroIce: return (0.039, 0.031, 0.094)
            case .auroraDawn: return (0.063, 0.031, 0.039)
            case .auroraEmber: return (0.060, 0.024, 0.020)
            case .auroraIce: return (0.024, 0.071, 0.102)
            case .auroraRose: return (0.063, 0.024, 0.060)
            }
        }

        /// Process-wide BACKGROUND — near-black with a whisper of
        /// hue. `HUDTheme.mapBackground` proxies through this.
        var backgroundColor: Color {
            let c = bgRGB
            return Color(red: c.r, green: c.g, blue: c.b)
        }

        /// Card surface — the raised tier above bg. Inherits the
        /// theme's hue at +0.07 luminance, matching the legacy
        /// (0.13, 0.13, 0.14) vs (0.06, 0.06, 0.07) ratio on Original.
        var cardBackground: Color {
            offset(by: 0.070)
        }

        /// Sunken surface — input fields, search bars, sub-panels.
        /// Slightly above bg so it reads as recessed against cards.
        var inputBackground: Color {
            offset(by: 0.030)
        }

        /// Top-bar / sticky header tier. Barely above bg so it
        /// reads as a continuation of the root surface, just
        /// enough to differentiate when content scrolls beneath.
        var headerBackground: Color {
            offset(by: 0.010)
        }

        /// Hairline stroke on cards + buttons. Bigger lift so the
        /// outline registers without going to flat white-on-tint.
        var cardBorder: Color {
            offset(by: 0.160)
        }

        /// Add `delta` to every channel of `bgRGB`, clamped to [0,1].
        /// Preserves the theme's hue + chroma; only luminance shifts.
        private func offset(by delta: Double) -> Color {
            let c = bgRGB
            return Color(
                red: min(1.0, c.r + delta),
                green: min(1.0, c.g + delta),
                blue: min(1.0, c.b + delta)
            )
        }

        /// Alternate AppIcon set name registered under
        /// `CFBundleAlternateIcons`. `nil` = primary `AppIcon` (the
        /// original red+black art).
        var alternateIconName: String? {
            switch self {
            case .original: return nil
            case .glacier: return "AppIcon-Glacier"
            case .sunset: return "AppIcon-Sunset"
            case .carbon: return "AppIcon-Carbon"
            case .bluebird: return "AppIcon-Bluebird"
            case .emerald: return "AppIcon-Emerald"
            case .lagoon: return "AppIcon-Lagoon"
            case .rose: return "AppIcon-Rose"
            case .solar: return "AppIcon-Solar"
            case .pine: return "AppIcon-Pine"
            case .sapphire: return "AppIcon-Sapphire"
            case .lavender: return "AppIcon-Lavender"
            case .cherry: return "AppIcon-Cherry"
            case .magenta: return "AppIcon-Magenta"
            case .mintFrost: return "AppIcon-MintFrost"
            case .ember: return "AppIcon-Ember"
            case .powder: return "AppIcon-Powder"
            case .whiteout: return "AppIcon-Whiteout"
            case .aurora: return "AppIcon-Aurora"
            case .fireside: return "AppIcon-Fireside"
            case .timber: return "AppIcon-Timber"
            case .evergreen: return "AppIcon-Evergreen"
            case .moonlit: return "AppIcon-Moonlit"
            case .nebula: return "AppIcon-Nebula"
            case .infrared: return "AppIcon-Infrared"
            case .retro: return "AppIcon-Retro"
            case .stardust: return "AppIcon-Stardust"
            case .crevasse: return "AppIcon-Crevasse"
            case .olive: return "AppIcon-Olive"
            case .tidepool: return "AppIcon-Tidepool"
            case .violet: return "AppIcon-Violet"
            case .retroIce: return "AppIcon-RetroIce"
            case .auroraDawn: return "AppIcon-AuroraDawn"
            case .auroraEmber: return "AppIcon-AuroraEmber"
            case .auroraIce: return "AppIcon-AuroraIce"
            case .auroraRose: return "AppIcon-AuroraRose"
            }
        }

        /// Name of a regular `Image(named:)`-loadable imageset that
        /// duplicates the variant's 1024 light PNG. AppIcon* sets
        /// themselves can't be loaded as plain images reliably across
        /// iOS versions, so each variant ships a sibling preview set.
        var previewImageName: String {
            switch self {
            case .original: return "IconPreviewOriginal"
            case .glacier: return "IconPreviewGlacier"
            case .sunset: return "IconPreviewSunset"
            case .carbon: return "IconPreviewCarbon"
            case .bluebird: return "IconPreviewBluebird"
            case .emerald: return "IconPreviewEmerald"
            case .lagoon: return "IconPreviewLagoon"
            case .rose: return "IconPreviewRose"
            case .solar: return "IconPreviewSolar"
            case .pine: return "IconPreviewPine"
            case .sapphire: return "IconPreviewSapphire"
            case .lavender: return "IconPreviewLavender"
            case .cherry: return "IconPreviewCherry"
            case .magenta: return "IconPreviewMagenta"
            case .mintFrost: return "IconPreviewMintFrost"
            case .ember: return "IconPreviewEmber"
            case .powder: return "IconPreviewPowder"
            case .whiteout: return "IconPreviewWhiteout"
            case .aurora: return "IconPreviewAurora"
            case .fireside: return "IconPreviewFireside"
            case .timber: return "IconPreviewTimber"
            case .evergreen: return "IconPreviewEvergreen"
            case .moonlit: return "IconPreviewMoonlit"
            case .nebula: return "IconPreviewNebula"
            case .infrared: return "IconPreviewInfrared"
            case .retro: return "IconPreviewRetro"
            case .stardust: return "IconPreviewStardust"
            case .crevasse: return "IconPreviewCrevasse"
            case .olive: return "IconPreviewOlive"
            case .tidepool: return "IconPreviewTidepool"
            case .violet: return "IconPreviewViolet"
            case .retroIce: return "IconPreviewRetroIce"
            case .auroraDawn: return "IconPreviewAuroraDawn"
            case .auroraEmber: return "IconPreviewAuroraEmber"
            case .auroraIce: return "IconPreviewAuroraIce"
            case .auroraRose: return "IconPreviewAuroraRose"
            }
        }
    }

    // MARK: - Storage

    private static let themeKey = "powdermeet.theme.id"

    /// Legacy keys used when icon and accent were two independent axes.
    /// Read once at init for upgrade migration, never written again.
    private static let legacyAccentKey = "powdermeet.theme.accent"
    private static let legacyIconKey = "powdermeet.theme.appIcon"

    /// Currently-applied theme. Setting persists + applies the icon
    /// alternate. HUD views that read `HUDTheme.accent` /
    /// `HUDTheme.mapBackground` re-render automatically through
    /// Swift Observation tracking.
    var activeTheme: Theme {
        didSet {
            guard oldValue != activeTheme else { return }
            UserDefaults.standard.set(activeTheme.rawValue, forKey: Self.themeKey)
            generation &+= 1
            applyAlternateAppIcon(activeTheme)
        }
    }

    /// Calls `UIApplication.setAlternateIconName(_:)` for the chosen
    /// theme. iOS no-ops if the requested name is already current and
    /// silently rejects a swap if the alternate isn't bundled — both
    /// fine, the completion error is logged and swallowed in DEBUG.
    private func applyAlternateAppIcon(_ theme: Theme) {
        let target = theme.alternateIconName
        let app = UIApplication.shared
        guard app.supportsAlternateIcons else { return }
        if app.alternateIconName == target { return }
        app.setAlternateIconName(target) { error in
            if let error {
                #if DEBUG
                print("ThemeManager: setAlternateIconName(\(target ?? "nil")) failed: \(error)")
                #endif
            }
        }
    }

    /// Increments on every theme change. RootView reads it inside
    /// `.id(...)` so a swap forces the picker UI's "selected" row
    /// indicators to re-render through Swift Observation tracking.
    var generation: Int = 0

    private init() {
        if let raw = UserDefaults.standard.string(forKey: Self.themeKey),
           let theme = Theme(rawValue: raw) {
            self.activeTheme = theme
            return
        }
        // Legacy 2-axis migration: a returning user had an icon stored
        // under `powdermeet.theme.appIcon`; honor it.
        let legacyIcon = UserDefaults.standard.string(forKey: Self.legacyIconKey)
        let migrated: Theme
        switch legacyIcon {
        // Legacy 2-axis icons that survived curation still migrate;
        // culled ones (avalanche, alpenglow, verdant, …) fall through
        // to Original.
        case "glacier": migrated = .glacier
        default:        migrated = .original
        }
        self.activeTheme = migrated
        UserDefaults.standard.set(migrated.rawValue, forKey: Self.themeKey)
        UserDefaults.standard.removeObject(forKey: Self.legacyAccentKey)
        UserDefaults.standard.removeObject(forKey: Self.legacyIconKey)
    }

    /// Reset theme to the launch default. Called on account deletion
    /// so a fresh account that signs in next on this device starts
    /// clean. Sign-out alone does NOT reset.
    func resetToDefault() {
        activeTheme = .original
    }
}
