//
//  MountainLinesTexture.swift
//  PowderMeet
//
//  The app's brand watermark: a topographic contour-line motif
//  (`TopoLines`, generated by `tools/generate_topo_texture.py`),
//  template-tinted so it inherits the active theme accent.
//
//  It's deliberately a SYSTEM, not a one-off. Real product design
//  uses an ambient texture like this as a quiet through-line — present
//  on immersive flow screens, a whisper in chrome, and never behind
//  dense content. Three intentional placements express that:
//
//   • `.ambient`   — full-bleed. The lines surface from the TOP and
//     BOTTOM edges and fade toward a low floor through the middle, so
//     content stays readable but the motif is genuinely present (not
//     the near-invisible corner slivers the old radial clear left).
//     Used on auth + every onboarding step.
//
//   • `.headerBand` — emerges from the very top edge, dissolves within
//     header height. Behind page-header chrome only.
//
//   • `.panel` — a faint top-emerge wash for big passive surfaces:
//     sheet headers, the profile hero, empty states. Threads the
//     motif through the app without ever touching lists / map / nav.
//
//  All clamp to their container (source PNG is 2048², a bare
//  scaledToFill would blow out the layout) and refuse gestures.
//

import SwiftUI

struct MountainLinesTexture: View {

    enum Placement {
        /// Full-bleed, top+bottom emerge, mid floor. Flow screens.
        case ambient
        /// Top-anchored band behind page-header chrome.
        case headerBand
        /// Faint top-emerge wash for passive panels / hero / empties.
        case panel
    }

    var placement: Placement = .ambient

    /// Stroke color. Defaults to the active HUD accent so the texture
    /// re-tints automatically through Swift Observation tracking.
    var tint: Color = HUDTheme.accent

    var body: some View {
        switch placement {
        case .ambient:
            ambientBody
        case .headerBand:
            // Fills a small header `.background` — fade across its full
            // (already short) height.
            bandBody(opacity: 0.05, capHeight: nil)
        case .panel:
            // Fills a whole sheet/hero — confine the wash to a fixed
            // top strip so it reads as a header accent, not a
            // half-screen tint, regardless of container size.
            bandBody(opacity: 0.045, capHeight: 200)
        }
    }

    // MARK: - Ambient (auth + onboarding)

    /// Lines emerge faintly from the top AND bottom edges and fade to
    /// a near-zero floor through the middle — a whisper-weight frame
    /// behind the auth / onboarding content, never competing with it.
    /// (Peak alpha dialed back 0.24→0.09 and the edge masks softened;
    /// it had been reading far too heavy on the sign-in screen.)
    private var ambientBody: some View {
        GeometryReader { geo in
            Image("TopoLines")
                .resizable()
                .renderingMode(.template)
                .scaledToFill()
                .frame(width: geo.size.width * 1.15,
                       height: geo.size.height * 1.15)
                .frame(width: geo.size.width, height: geo.size.height)
                .clipped()
                .foregroundColor(tint.opacity(0.09))
                .mask(
                    LinearGradient(
                        gradient: Gradient(stops: [
                            .init(color: .black.opacity(0.65),  location: 0.00),
                            .init(color: .black.opacity(0.22),  location: 0.30),
                            .init(color: .black.opacity(0.06),  location: 0.50),
                            .init(color: .black.opacity(0.22),  location: 0.70),
                            .init(color: .black.opacity(0.65),  location: 1.00),
                        ]),
                        startPoint: .top,
                        endPoint: .bottom
                    )
                )
        }
        .ignoresSafeArea()
        .allowsHitTesting(false)
    }

    // MARK: - Top-emerge band (header + panel)

    /// Lines surface from the top edge and dissolve downward. When
    /// `capHeight` is set the wash is confined to a fixed top strip of
    /// that height, top-aligned (so a full-sheet container still only
    /// gets a header-sized accent); when nil it fades across the
    /// container's full height (small header `.background`). Lives
    /// inside a `.background`, so it's clipped and can't bleed.
    private func bandBody(opacity: Double, capHeight: CGFloat?) -> some View {
        GeometryReader { geo in
            let h = capHeight.map { min($0, geo.size.height) } ?? geo.size.height
            Image("TopoLines")
                .resizable()
                .renderingMode(.template)
                .scaledToFill()
                .frame(width: geo.size.width, height: h)
                .clipped()
                .foregroundColor(tint.opacity(opacity))
                .mask(
                    LinearGradient(
                        gradient: Gradient(stops: [
                            .init(color: .black,               location: 0.00),
                            .init(color: .black.opacity(0.55), location: 0.40),
                            .init(color: .clear,               location: 1.00),
                        ]),
                        startPoint: .top,
                        endPoint: .bottom
                    )
                )
                .frame(width: geo.size.width, height: geo.size.height,
                       alignment: .top)
        }
        // Flatten the template-tinted 2048² image + gradient mask into one
        // offscreen GPU layer. It's static (re-tints only on theme change),
        // so compositing it once is far cheaper than re-rasterizing the
        // stack on any container resize.
        .drawingGroup()
        .allowsHitTesting(false)
    }
}
