//
//  ImportedRunPersistence.swift
//  PowderMeet
//
//  Version-tolerant wire persistence for imported and live-recorded runs.
//  The rebuilt client authors richer attribution fields, but an installed
//  development build must not make every parser appear broken while the
//  corresponding backend migrations are still pending.
//

import Foundation
import Supabase

nonisolated enum ImportedRunSchemaCompatibility {
    private static let expandedColumns = [
        "raw_source_identity",
        "dataset_version",
        "matched_segment_ids",
        "edge_observations",
        "match_confidence",
        "match_method",
        "equipment_id_at_activity"
    ]

    /// Retry only when PostgREST/Postgres explicitly says one of the newer
    /// attribution columns is absent. Authentication, RLS, validation, and
    /// connectivity failures must remain real failures rather than being
    /// hidden behind a second request.
    static func shouldRetryLegacy(after error: Error) -> Bool {
        shouldRetryLegacy(message: error.localizedDescription)
    }

    static func shouldRetryLegacy(message: String) -> Bool {
        missingExpandedColumn(message: message) != nil
    }

    static func missingExpandedColumn(message: String) -> String? {
        let text = message.lowercased()
        guard text.contains("schema cache")
            || text.contains("pgrst204")
            || text.contains("does not exist")
            || text.contains("unknown column") else { return nil }
        return expandedColumns.first(where: text.contains)
    }
}

/// Distinguishes evidence-backed trail labels from UI fallbacks. Persisted
/// fallbacks from older builds are intentionally recognized so re-importing
/// the same source can repair the row instead of being blocked as a duplicate.
nonisolated enum ImportedRunNameQuality {
    /// One naming rule for every activity source and match tier. A graph edge
    /// can be a nameless OSM fragment inside a named trail group, so reading
    /// `edge.attributes.trailName` directly is not sufficient even after a
    /// high-confidence topology match. Resolve through `MountainNaming`, use
    /// the bare trail identity because difficulty is stored separately, and
    /// refuse synthetic fallbacks such as "Run".
    static func evidenceBackedTrailName(
        for edge: GraphEdge,
        naming: MountainNaming
    ) -> String? {
        concreteName(naming.edgeLabel(edge, style: .bareName))
            ?? concreteName(edge.attributes.trailName)
    }

    static func concreteName(_ raw: String?) -> String? {
        guard let raw else { return nil }
        let name = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return isConcrete(name) ? name : nil
    }

    static func isConcrete(_ raw: String?) -> Bool {
        guard let raw else { return false }
        let name = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !name.isEmpty else { return false }
        let normalized = name.lowercased()
        if normalized == "run" || normalized == "imported run" || normalized == "whole day" {
            return false
        }
        // These are generated by Trail.displayName / MountainNaming when the
        // source has no trail identity. They must not count as a resolved name.
        let unnamedPattern = #"^unnamed (green|blue|black|double black|terrain park|unknown) trail(?:\s*·\s*#\d+)?$"#
        if normalized.range(of: unnamedPattern, options: .regularExpression) != nil { return false }
        let fallbackPattern = #"^(green|blue|black|double black|terrain park)?\s*run\s*(·.*)?$"#
        return normalized.range(of: fallbackPattern, options: .regularExpression) == nil
    }

    static func shouldUpgrade(
        existingName: String?,
        existingConfidence: Double?,
        candidateName: String?,
        candidateConfidence: Double
    ) -> Bool {
        guard isConcrete(candidateName) else { return false }
        if !isConcrete(existingName) { return true }
        return candidateConfidence > (existingConfidence ?? 0) + 0.01
    }
}

/// Superset row used when the observation-provenance migrations are present.
/// Optional source fields also allow this one shape to serve backup restores.
nonisolated struct ImportedRunWriteRow: Encodable {
    let profile_id: String
    let resort_id: String?
    let edge_id: String?
    let difficulty: String?
    let speed_ms: Double
    let peak_speed_ms: Double?
    let duration_s: Double
    let vertical_m: Double
    let distance_m: Double
    let max_grade_deg: Double
    let run_at: Date
    let dedup_hash: String
    let source: String?
    let source_file_hash: String?
    let raw_source_identity: String?
    let dataset_version: String?
    let matched_segment_ids: [String]
    let edge_observations: [EdgePaceObservation]
    let match_confidence: Double
    let match_method: String
    let equipment_id_at_activity: UUID?
    let trail_name: String?
    let conditions_fp: String

    var withoutEdgeObservations: some Encodable {
        ObservationCompatibleImportedRunWriteRow(
            profile_id: profile_id,
            resort_id: resort_id,
            edge_id: edge_id,
            difficulty: difficulty,
            speed_ms: speed_ms,
            peak_speed_ms: peak_speed_ms,
            duration_s: duration_s,
            vertical_m: vertical_m,
            distance_m: distance_m,
            max_grade_deg: max_grade_deg,
            run_at: run_at,
            dedup_hash: dedup_hash,
            source: source,
            source_file_hash: source_file_hash,
            raw_source_identity: raw_source_identity,
            dataset_version: dataset_version,
            matched_segment_ids: matched_segment_ids,
            match_confidence: match_confidence,
            match_method: match_method,
            equipment_id_at_activity: equipment_id_at_activity,
            trail_name: trail_name,
            conditions_fp: conditions_fp
        )
    }

    var legacy: some Encodable {
        LegacyImportedRunWriteRow(
            profile_id: profile_id,
            resort_id: resort_id,
            edge_id: RecordedPaceEvidence.legacyEdgeID(edge_id, method: match_method),
            difficulty: difficulty,
            speed_ms: speed_ms,
            peak_speed_ms: peak_speed_ms,
            duration_s: duration_s,
            vertical_m: vertical_m,
            distance_m: distance_m,
            max_grade_deg: max_grade_deg,
            run_at: run_at,
            dedup_hash: dedup_hash,
            source: source,
            source_file_hash: source_file_hash,
            trail_name: trail_name,
            conditions_fp: conditions_fp
        )
    }
}

/// Transitional production shape: all directed-match and equipment attribution
/// fields are available, while the later per-edge observation JSON migration is
/// still pending. Keeping this distinct prevents a single missing column from
/// discarding otherwise supported ski-specific evidence.
private nonisolated struct ObservationCompatibleImportedRunWriteRow: Encodable {
    let profile_id: String
    let resort_id: String?
    let edge_id: String?
    let difficulty: String?
    let speed_ms: Double
    let peak_speed_ms: Double?
    let duration_s: Double
    let vertical_m: Double
    let distance_m: Double
    let max_grade_deg: Double
    let run_at: Date
    let dedup_hash: String
    let source: String?
    let source_file_hash: String?
    let raw_source_identity: String?
    let dataset_version: String?
    let matched_segment_ids: [String]
    let match_confidence: Double
    let match_method: String
    let equipment_id_at_activity: UUID?
    let trail_name: String?
    let conditions_fp: String
}

/// May-2026 production schema. Deliberately excludes only the richer August
/// attribution fields; run history, measured metrics, names, deduplication,
/// and source provenance remain intact.
private nonisolated struct LegacyImportedRunWriteRow: Encodable {
    let profile_id: String
    let resort_id: String?
    let edge_id: String?
    let difficulty: String?
    let speed_ms: Double
    let peak_speed_ms: Double?
    let duration_s: Double
    let vertical_m: Double
    let distance_m: Double
    let max_grade_deg: Double
    let run_at: Date
    let dedup_hash: String
    let source: String?
    let source_file_hash: String?
    let trail_name: String?
    let conditions_fp: String
}

extension SupabaseManager {
    /// Inserts exact new identities and returns their dedup hashes. A schema
    /// mismatch gets one deterministic retry with the legacy payload; all
    /// other errors surface unchanged.
    @MainActor
    func upsertImportedRunRows(_ rows: [ImportedRunWriteRow]) async throws -> Set<String> {
        guard !rows.isEmpty else { return [] }

        struct InsertedIdentity: Decodable {
            let dedup_hash: String
        }

        do {
            let inserted: [InsertedIdentity] = try await client
                .from("imported_runs")
                .upsert(
                    rows,
                    onConflict: "profile_id,dedup_hash",
                    ignoreDuplicates: true
                )
                .select("dedup_hash")
                .execute()
                .value
            let insertedHashes = Set(inserted.map(\.dedup_hash))
            return insertedHashes.union(
                await upgradePreviouslyGenericRuns(rows, excluding: insertedHashes)
            )
        } catch {
            guard let missingColumn = ImportedRunSchemaCompatibility.missingExpandedColumn(
                message: error.localizedDescription
            ) else {
                throw error
            }

            if missingColumn == "edge_observations" {
                do {
                    AppLog.importer.debug(
                        "imported_runs edge observations are pending; preserving other attribution fields"
                    )
                    let inserted: [InsertedIdentity] = try await client
                        .from("imported_runs")
                        .upsert(
                            rows.map(\.withoutEdgeObservations),
                            onConflict: "profile_id,dedup_hash",
                            ignoreDuplicates: true
                        )
                        .select("dedup_hash")
                        .execute()
                        .value
                    let insertedHashes = Set(inserted.map(\.dedup_hash))
                    return insertedHashes.union(
                        await upgradePreviouslyGenericRuns(rows, excluding: insertedHashes)
                    )
                } catch {
                    guard ImportedRunSchemaCompatibility.shouldRetryLegacy(after: error) else {
                        throw error
                    }
                }
            }

            AppLog.importer.debug(
                "imported_runs attribution schema is pending; retrying compatible payload"
            )
            let inserted: [InsertedIdentity] = try await client
                .from("imported_runs")
                .upsert(
                    rows.map(\.legacy),
                    onConflict: "profile_id,dedup_hash",
                    ignoreDuplicates: true
                )
                .select("dedup_hash")
                .execute()
                .value
            let insertedHashes = Set(inserted.map(\.dedup_hash))
            return insertedHashes.union(
                await upgradePreviouslyGenericRuns(rows, excluding: insertedHashes)
            )
        }
    }

    /// Exact re-imports remain idempotent, but a row written before its graph
    /// was available may be upgraded when reconstruction now provides a real
    /// trail and stronger match. This never creates a second run and never
    /// replaces a concrete label with another equally weak guess.
    @MainActor
    private func upgradePreviouslyGenericRuns(
        _ rows: [ImportedRunWriteRow],
        excluding insertedHashes: Set<String>
    ) async -> Set<String> {
        let candidates = rows.filter {
            !insertedHashes.contains($0.dedup_hash)
                && ImportedRunNameQuality.isConcrete($0.trail_name)
        }
        guard !candidates.isEmpty else { return [] }

        struct ExistingRow: Decodable {
            let dedup_hash: String
            let trail_name: String?
            let match_confidence: Double?
        }
        let existing: [ExistingRow]
        do {
            existing = try await client.from("imported_runs")
                .select("dedup_hash,trail_name,match_confidence")
                .eq("profile_id", value: candidates[0].profile_id)
                .in("dedup_hash", values: candidates.map(\.dedup_hash))
                .execute()
                .value
        } catch {
            guard ImportedRunSchemaCompatibility.shouldRetryLegacy(after: error) else {
                AppLog.importer.debug("duplicate-name audit skipped: \(error.localizedDescription)")
                return []
            }
            struct CoreExistingRow: Decodable {
                let dedup_hash: String
                let trail_name: String?
            }
            do {
                let core: [CoreExistingRow] = try await client.from("imported_runs")
                    .select("dedup_hash,trail_name")
                    .eq("profile_id", value: candidates[0].profile_id)
                    .in("dedup_hash", values: candidates.map(\.dedup_hash))
                    .execute()
                    .value
                // Legacy rows have no confidence evidence. Protect an already
                // concrete name from replacement while still allowing a
                // generic/null name to be repaired.
                existing = core.map {
                    ExistingRow(
                        dedup_hash: $0.dedup_hash,
                        trail_name: $0.trail_name,
                        match_confidence: ImportedRunNameQuality.isConcrete($0.trail_name)
                            ? 1
                            : nil
                    )
                }
            } catch {
                AppLog.importer.debug("legacy duplicate-name audit skipped: \(error.localizedDescription)")
                return []
            }
        }
        let existingByHash = Dictionary(
            existing.map { ($0.dedup_hash, $0) },
            uniquingKeysWith: { first, _ in first }
        )

        struct UpgradePayload: Encodable {
            let resort_id: String?
            let edge_id: String?
            let difficulty: String?
            let dataset_version: String?
            let matched_segment_ids: [String]
            let match_confidence: Double
            let match_method: String
            let equipment_id_at_activity: UUID?
            let raw_source_identity: String?
            let trail_name: String?
        }
        struct CoreUpgradePayload: Encodable {
            let resort_id: String?
            let edge_id: String?
            let difficulty: String?
            let trail_name: String?

            enum CodingKeys: String, CodingKey {
                case resort_id, edge_id, difficulty, trail_name
            }

            func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: CodingKeys.self)
                try values.encodeIfPresent(resort_id, forKey: .resort_id)
                // Explicit null clears a prior learning key when an exact
                // generic-name repair now has only route evidence.
                try values.encode(edge_id, forKey: .edge_id)
                try values.encodeIfPresent(difficulty, forKey: .difficulty)
                try values.encodeIfPresent(trail_name, forKey: .trail_name)
            }
        }

        var upgraded: Set<String> = []
        for candidate in candidates {
            guard let prior = existingByHash[candidate.dedup_hash],
                  ImportedRunNameQuality.shouldUpgrade(
                    existingName: prior.trail_name,
                    existingConfidence: prior.match_confidence,
                    candidateName: candidate.trail_name,
                    candidateConfidence: candidate.match_confidence
                  ) else { continue }
            do {
                do {
                    try await client.from("imported_runs")
                        .update(UpgradePayload(
                            resort_id: candidate.resort_id,
                            edge_id: candidate.edge_id,
                            difficulty: candidate.difficulty,
                            dataset_version: candidate.dataset_version,
                            matched_segment_ids: candidate.matched_segment_ids,
                            match_confidence: candidate.match_confidence,
                            match_method: candidate.match_method,
                            equipment_id_at_activity: candidate.equipment_id_at_activity,
                            raw_source_identity: candidate.raw_source_identity,
                            trail_name: candidate.trail_name
                        ))
                        .eq("profile_id", value: candidate.profile_id)
                        .eq("dedup_hash", value: candidate.dedup_hash)
                        .execute()
                } catch {
                    guard ImportedRunSchemaCompatibility.shouldRetryLegacy(after: error) else {
                        throw error
                    }
                    try await client.from("imported_runs")
                        .update(CoreUpgradePayload(
                            resort_id: candidate.resort_id,
                            edge_id: RecordedPaceEvidence.legacyEdgeID(
                                candidate.edge_id, method: candidate.match_method
                            ),
                            difficulty: candidate.difficulty,
                            trail_name: candidate.trail_name
                        ))
                        .eq("profile_id", value: candidate.profile_id)
                        .eq("dedup_hash", value: candidate.dedup_hash)
                        .execute()
                }
                upgraded.insert(candidate.dedup_hash)
            } catch {
                AppLog.importer.debug("duplicate-name upgrade skipped: \(error.localizedDescription)")
            }
        }
        return upgraded
    }
}
